manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  # projects:
  #   - name: zmk
  #     remote: zmkfirmware
  #     revision: main
  #     import: app/west.yml
  projects:
    - name: zmk
      remote: Deemen17
      revision: display/bongo-cat-widget
      import: app/west.yml
  self:
    path: config
